### PR TITLE
chore: configured arbitrary values in index.html

### PR DESCRIPTION
**Pull request by KevinRebakure**

### CODE REVIEW

**Review by tuyishimejohnson — COMMENTED** [review]
It seems you changed everything that you were supposed to change. You can keep on with the project

**Review by AL2002MI08 — COMMENTED** [review]
Great work

**Review by AL2002MI08 — APPROVED** [review]
Great work!!

**Review by tuyishimejohnson — APPROVED** [review]
Everything is fine, you can keep on with the project.

**Pull request merged**
